### ISSUE TITLE
Binaries should link openssl statically

### ISSUE THREAD

**Issue by Luthaf** [rust-lang-nursery/multirust-rs#123]
See http://users.rust-lang.org/t/expect-disruptions-to-multirust-rs-self-updates/5015/2 for the error.

**Comment by brson** [comment]
I've been looking at this all day and I still haven't figured out why our travis setup isn't producing statically-linked bins. My only suspicion is that running `cargo test` outside of the docker image is overwriting the dockered bins, but I haven't proven it yet.

**Comment by Luthaf** [comment]
This works, but I run into another issue. See #131.
