### ISSUE TITLE
Multirust should check PATH for ~/.cargo/bin on self update

### ISSUE THREAD

**Issue by Luthaf** [rust-lang-nursery/multirust-rs#131]
I had `~/.multirust/bin` in my path, but not `~/.cargo/bin`. Trying to self update gives me:

```
$ multirust self update
downloading file from: 'https://github.com/Diggsey/multirust-rs-binaries/raw/master/x86_64-unknown-linux-gnu/multirust-rs.sha256'
downloading file from: 'https://github.com/Diggsey/multirust-rs-binaries/raw/master/x86_64-unknown-linux-gnu/multirust-rs'
Installing...
info: updating existing installation

stable revision:

rustc 1.7.0 (a5d1e7a59 2016-02-29)
Could not execute process `rustc -vV` (never executed)

Caused by:
  No such file or directory (os error 2)
(failed to run cargo)
```

If I add `~/.cargo/bin` to my path, I get an error about metadata, and then I can install the toolchains.

**Comment by brson** [comment]
I think this `Could not execute process `rustc -vV` (never executed)` error is a symptom of another bug, not specifically related to self-update. `~/.cargo/bin` shouldn't be required on the `$PATH` or anything in rustup to work.

**Comment by Luthaf** [comment]
I though this was the cause because `rustc` used to be in `.multirust/bin` and is now in `.cargo/bin`. Tell me if I can do something to help debug this!
