### ISSUE TITLE
Add a --channel flag to `rustup target`?

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/multirust-rs#141]
With a default stable channel, I unfortunately can't do `rustup target add` or `target list` as it gives the error:

```
error: toolchain 'stable' does not support components
```

**Comment by brson** [comment]
@alexcrichton Do you like the default of operating on the active toolchain?

**Comment by alexcrichton** [comment]
Yeah I like the work flow of:

* Cargo build --target foo
* Ooops forgot the standard library
* rustup target add foo
* cargo build --target foo

(just less typing)
