### ISSUE TITLE
Bypassing the prompt on Windows

### ISSUE THREAD

**Issue by Ogeon** [rust-lang-nursery/multirust-rs#148]
I'm using `multirust-rs` to install Rust on AppVeyor (because of some problems with `rustup.sh`), but some update introduced a prompt during the installation. I would like to know if there is any way to bypass it, that I haven't found, or if that feature can be added.

**Comment by brson** [comment]
Pass `-y`.

**Comment by Ogeon** [comment]
Oh, yes, thank you. I couldn't find it when I looked for a flag, but I must have just missed it.
