### ISSUE TITLE
Keep only unique installed toolchain with (optionally) aliases instead of duplicating folders

### ISSUE THREAD

**Issue by pravic** [rust-lang-nursery/multirust-rs#149]
The following downloads the same toolchain - `i686-pc-windows-msvc-nightly` - multiply times:
```
multirust default nightly
multirust default msvc-nightly
multirust default i686-msvc-nightly
```

**Comment by brson** [comment]
Thank for the report. This is intended future work. The toolchain names need to be normalized internally.
