### ISSUE TITLE
rustup-setup.exe panics before install completes on windows

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/multirust-rs#181]
> Just tried this on Windows 8.1

> First of all, "Windows SmartScreen prevented an unrecognized app from running. Running this app might put your PC at risk. Publisher: Unknown Publisher".

> After the confirmation Y of Continue? (Y/n) the console window closes very quickly. I noticed some panic message before the window closed, but it disappears too quickly to be read. HKEY_CURRENT_USER/Environment/PATH is not updated, some binaries however appear in %USERNAME%\.cargo.

[Source](https://internals.rust-lang.org/t/beta-testing-rustup-rs/3316/10?u=brson).

**Comment by petrochenkov** [comment]
>the console window closes very quickly

`rustup-setup.exe` not reusing the existing console from which it's run, but creating its own console instance, is probably a problem too.

**Comment by brson** [comment]
> rustup-setup.exe not reusing the existing console from which it's run, but creating its own console instance, is probably a problem too.

@petrochenkov When I run rustup-setup.exe from a command console or mintty console it does not create a new console. I've filed [another issue to deal with that specifically](https://github.com/rust-lang-nursery/multirust-rs/issues/225).

And I've changed this issue to be just about the mystery error and closing console. [Here's another bug about windows PATH not being configured](https://github.com/rust-lang-nursery/multirust-rs/issues/226).

**Comment by brson** [comment]
Agh! I reproduced this this morning but no longer can. When I run the restup-setup.exe from exe.rustup.rs it opens a console, waits for confirmation, does the install, then waits for keypress as expected.

**Comment by brson** [comment]
Haha, ok, I can reproduce what this is probably seeing by having a compile running while trying to install, making it impossible to delete the bins. What I can probably do is make it so interactive installs on windows display the error, then wait for keypress.
