### ISSUE TITLE
rustup --quiet

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang-nursery/multirust-rs#186]
I’d like to run `rustup` in a daily cron job to automatically keep toolchains (in particular `nightly`) up to date. Cron is configured to send the output of jobs by email, if any. So jobs should only produce any output if something goes wrong.

I’d like to add a `--quiet` command-line option to `rustup` which would disable calls to the `info!` macro (like calls to `verbose!` are disabled unless `--verbose` is given) and disable printing of downloads progress.

@brson, what do you think of having a global (`lazy_static!` with `RWLock`?) log level, rather than threading a `verbose` boolean through calls everywhere?

**Comment by SimonSapin** [comment]
I’ve found a work-around.

```
6 16	* * *	(RUSTUP_HOME=$HOME/tmp/rustup CARGO_HOME=$HOME/tmp/cargo-home PATH="$HOME/tmp/cargo-home/bin:$PATH" rustup > /dev/null) 2>&1 | grep -v '^info:'

**Comment by dbaron** [comment]
In case it's of interest to anyone else, I wanted something somewhat similar... but different.  As a user of stable rust, I also want rustup in a cron job -- but I want to get the email when it updates something, but want it to stay silent when nothing changes.  (Getting errors would be nice too... but I don't know what they look like so it's hard to test for.)

The solution I ended up with was:
```
7 0 * * * $HOME/.cargo/bin/rustup update 2>&1 | grep -1000 "\(downloading\|installing\|updated\)"
```
(And, yes, that's a randomly generated time of day that just happened to be 00:07.)
