### ISSUE TITLE
Use junctions instead of symlinks on windows

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/multirust-rs#188]
Perhaps the tests could automatically be disabled, or there's an option to run the entire test suite "but the symlink tests" which is disabled by default?

**Comment by brson** [comment]
Supposedly we can use junctions without admin privileges so my long-term plan is to rewrite the code to not require admin.

**Comment by brson** [comment]
Well, not long-term. Pretty short-term.

**Comment by Diggsey** [comment]
The test suite is fixed with #184 but I'll leave this issue open to track the junctions feature.

**Comment by brson** [comment]
Thanks @Diggsey !
