### ISSUE TITLE
`run` doesn't pass empty arguments

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/multirust-rs#190]
[Source](https://internals.rust-lang.org/t/beta-testing-rustup-rs/3316/21?u=brson)

```
rustup run stable cargo build --verbose --no-default-features --features ""
```

```
Expected argument for flag '--features' but reached end of arguments.
```

**Comment by brson** [comment]
This is *probably* a bug in clap or me not understanding clap. The code is pretty straightforward. `values_of("command")` is supposed to return multiple arguments but doesn't return the trailing empty argument. cc @kbknapp does this look familiar to you?

**Comment by brson** [comment]
"command" is defined as `Arg::with_name("command").required(true).multiple(true))`

**Comment by kbknapp** [comment]
@brson I think that's a docopt error message, or at least it's not one from clap. The error clap would have given in the same scenario (expecting an argument value but not getting one) would be:

```
$ rustup run stable cargo build --verbose --no-default-features --features
error: The argument '--features <feature>...' requires a value but none was supplied

USAGE:
    fake-rs [FLAGS] --features <feature>...

For more information try --help
```

I also just tested it with the empty string: `--features ""` which doesn't give an error. Empty values are allowed by default.

Side note, you can force it to be an error with the [`Arg::empty_values(false)`](http://kbknapp.github.io/clap-rs/clap/struct.Arg.html#method.empty_values) if that's desired.

**Comment by kbknapp** [comment]
@brson Thinking about it, I think it's because those arguments are being passed to `cargo`, which explains the error message.

**Comment by brson** [comment]
Yes it's because the error came from cargo. I'll keep looking into it. Thanks

**Comment by kbknapp** [comment]
@brson Ah ok, I misunderstood how it was running, I wasn't thinking the entire `stable cargo build --verbose --no-default-features --features ""` was being passed. This may in fact be a bug, let me look into it a little deeper I'll get back.

**Comment by brson** [comment]
@kbknapp here's a test case https://gist.github.com/brson/2e4a020b220500d9b2d24e4c2faef29c

**Comment by kbknapp** [comment]
Thanks! Checking it out now.

**Comment by kbknapp** [comment]
Just put in a PR to fix this!

**Comment by kbknapp** [comment]
v2.2.4 is on crates.io

**Comment by brson** [comment]
\o/ @kbknapp Thanks for the quick update! I'm pulling it in now.
