### ISSUE TITLE
Make `override list` not look horrible

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/multirust-rs#214]

**Comment by peschkaj** [comment]
Took at stab at this over at https://github.com/peschkaj/multirust-rs/commit/eb4c973a7444259dd094bde2ab1ebca9ea9c99fd

To speed up review, current output looks like this on Windows:

```
TOOLCHAIN               TARGET
--------------------    ----------------------------------------
nightly-x86_64-msvc     \\?\D:\src\peschkaj\coreutils
nightly-x86_64-msvc     \\?\D:\src\peschkaj\flaker
nightly-x86_64-msvc     \\?\D:\src\peschkaj\multirust-rs
nightly-x86_64-msvc     \\?\D:\src\peschkaj\todo
stable-msvc             \\?\D:\src\test-rustup
```

The `\\?\` isn't the prettiest thing on earth, but I wanted to get a :+1: or :-1: on the general output before attempting to format the string.

**Comment by brson** [comment]
Thanks for taking this @peschkaj.

It looks great. I think though that I expect the paths to be in the first column, the toolchain in the second. Is that easy to do?

Also can you rename `TARGET` to `PATH` since 'target' already means 'target triple'?

My only reservation here is about the column headers. None of the other `list` commands have that (they also only have one column).

If you tackle fixing the display paths on windows you might grep the source for the two occurrances of of the word `UNC` where I've noted this same problem and fix them all.

**Comment by peschkaj** [comment]
> I think though that I expect the paths to be in the first column, the toolchain in the second. Is that easy to do?

Very easy and I'll get on it.

> Also can you rename TARGET to PATH since 'target' already means 'target triple'?
> My only reservation here is about the column headers. None of the other list commands have that (they also only have one column).

Changing TARGET to PATH is easy enough to do. But in light of your second statement, I'll remove the header altogether. If we opt to add a header later, it's an easy enough change to make down the road.

I'll create a separate issue to clean up UNC paths just so there's a clean history.

**Comment by brson** [comment]
Fixed. Thanks @peschkaj!
