### ISSUE TITLE
Incorrect error message on metadata upgrade

### ISSUE THREAD

**Issue by vjackson725** [rust-lang-nursery/multirust-rs#219]
Error message is `"rustup's metadata is out of date. run rustup upgrade-data."`
and it should be `"rustup's metadata is out of date. run rustup self upgrade-data."`

Definition is at `multirust-rs/src/multirust/errors.rs` line 174
and test cases will need to change at `multirust-rs/tests/cli-misc.rs` lines 503 and 517

**Comment by brson** [comment]
Fixed!
