### ISSUE TITLE
rustup -v causes toolchains to update

### ISSUE THREAD

**Issue by cptroot** [rust-lang-nursery/multirust-rs#224]
Normally getting version information won't do anything except get the information, so it's alarming that getting version information would cause rustup to hit the network.

To repro:
Have an out of date rustup (say nightly hasn't been updated to most recent nightly yet.)
`rustup -v`
rustup gets updates to nightly.

**Comment by brson** [comment]
That's funny.

**Comment by brson** [comment]
This will be fixed by https://github.com/rust-lang-nursery/multirust-rs/pull/227

**Comment by vks** [comment]
I think this can be closed now.
