### ISSUE TITLE
Create a path formatter for Windows to remove UNC paths.

### ISSUE THREAD

**Issue by peschkaj** [rust-lang-nursery/multirust-rs#235]
On Windows, paths are being returned as `\\?\D:\src\peschkaj\coreutils`. When the server portion of the path is `\\?\`, we can safely remove it.

**Comment by peschkaj** [comment]
This is interesting - technically the `\\?\` is valid when combined with a full path, even if it is ugly. It's a direct result of calling `std::fs::canonicalize`. When we call `canonicalize()` on Windows, the `PathBuf`'s prefix is set to `\\?\DRIVE_LETTER`. 

I'm not sure where the best place to make this change would be. At a first guess, it looks like the best place would be in `OverrideDB::path_to_db_key` - instead of immediately returning the `Ok()` we can check the path and if path starts with `\\?\`, we can strip it out.

Does that seem sane, @brson?

**Comment by brson** [comment]
@peschkaj There are two places in `override_db` where paths are canonicalized, so I'd suggest putting the conversion directly in `utils::canonicalize_path` to get both of them.

cc @Diggsey I think it will be ok to change our canonicalization to strip out `\\?\` from Windows paths. That should make them Windows paths display nicer in the general case without risk of any ambiguity. What do you think?

**Comment by Diggsey** [comment]
I think it's fine for a human readable representation, but if we add a machine-readable form we obviously shouldn't do that there, so on the whole I'd prefer to do this when we display the path rather than when we canonicalize it.

**Comment by brson** [comment]
Fixed.
