### ISSUE TITLE
Can't update because of 'invalid target triple'

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/multirust-rs#248]
**If you are using rustup you are going to hit this. You can still run `rustup self update` to update rustup; you just won't be able to update your toolchains until this is fixed. I'll get a fix out as soon as I can.**

Today when I update I see

```
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
error: invalid target triple: 'i586-pc-windows-msvc'
```

`i586-pc-windows-msvc` is a new host platform. For some reason this string is being converted internally to a `TargetTriple`, and that conversion only supports a fixed set up targets.

The target triple logic needs to be changed to support more-or-less arbitrary strings.

**Comment by brson** [comment]
There's probably no way we can unbreak upgrades here. People are just going to have to reinstall.

**Comment by brson** [comment]
I'll try to get this fixed today.

**Comment by brson** [comment]
Oh! Actually `rustup self update` still works. It's just updating toolchains that doesn't.

**Comment by 0x0G** [comment]
Only `rustup update nightly` throw this error.
`rustup update stable` and `rustup update beta` works. But They create new dir "~/.multirust/toolchains/beta-x86_64-unknown-linux-gnu", but don't remove old dir "~/.multirust/toolchains/beta".

**Comment by brson** [comment]
@0x0G The extra directories are because `rustup` normalizes toolchain directories now. There's no compatibility code to rename them during upgrade, so rustup is just leaving them around.

**Comment by brson** [comment]
Reopening until this is deployed.

**Comment by brson** [comment]
The fix for this is deployed now. Sorry for the inconvenience.
