### ISSUE TITLE
[win] rustup setting wrong registry type for PATH

### ISSUE THREAD

**Issue by pravic** [rust-lang-nursery/multirust-rs#261]
[Here](https://github.com/rust-lang-nursery/multirust-rs/blob/master/src/multirust-cli/self_update.rs#L688). winreg [always uses](https://github.com/gentoo90/winreg-rs/blob/master/src/types.rs#L66-L82) `REG_SZ` type while environment often contains `REG_EXPAND_SZ`.

For example:
````cmd
CARGO_HOME=...
PATH=%CARGO_HOME%\bin;%PATH%
```

So after installing rustup, `PATH` environment is broken and cannot be expanded properly.

**Comment by brson** [comment]
This seems quite bad. If I understand you right at install rustup is *changing* the registry type from `REG_EXPAND_SZ` to `REG_SZ`, which breaks existing entries.

**Comment by brson** [comment]
I wonder if we need to be aware of anything when reading a `REG_EXPAND_SZ` key - we don't want to 'expand' it then write back the expanded version.

**Comment by brson** [comment]
Working on a patch.
