### ISSUE TITLE
CFG_CPUTYPE parameter not set

### ISSUE THREAD

**Issue by DaveKram** [rust-lang-nursery/multirust-rs#291]
Running curl https://sh.rustup.rs -sSf | sh on my linux box gives me:

`rustSetup.sh: CFG_CPUTYPE: parameter not set`

as I think my cputype isn't on the list in that switch case in rustup-setup.sh (running uname -m returns aarch64). And the error being thrown uses $CFG_CPUTYPE instead of _cputype for unknown CPU types.

**Comment by brson** [comment]
Thanks for the report. This will be fixed by https://github.com/rust-lang-nursery/multirust-rs/pull/310.

I'll try to get it deployed today. I'd love to hear further feedback about whether you get aarch64 working with rustup as that is a really bleeding-edge toolchain that few are testing.
