### ISSUE TITLE
Rustup installs i686 versions on 64-bit Windows

### ISSUE THREAD

**Issue by White-Oak** [rust-lang-nursery/multirust-rs#296]
I had to manually specify x86_64-pc-windows-gnu triple to get 64-bit version.
Is it intended?

**Comment by nodakai** [comment]
It appears that win.rustup.rs is (sort of) an alias to
https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-setup.exe
(32 bit Mingw build)

**Comment by brson** [comment]
This is intended, for two reasons: 1) I'd much rather have users download a single program than have to pick between 32-bit and 64-bit builds (or worse - between 32/64/gnu/msvc), 2) There's no particular reason to tie the default architecture to the architecture of the download.

Right now you can switch to a 64-bit toolchains by installing them explicitly, like `rustup default nightly-x86_64-pc-windows-gnu`.

I suspect that my preferred ultimate solution will be to have a configuration option for default host. At install time (perhaps just on windows), we'll mention "oh, and this is the target you'll build for by default", and then it can be changed interactively (or via command line switch).

**Comment by brson** [comment]
In the meantime, if you really need a build that defaults to 64-bit you can still download it from the "other installation methods" section of the README.

**Comment by brson** [comment]
[Here's a bug on the default host](https://github.com/rust-lang-nursery/multirust-rs/issues/309).

**Comment by brson** [comment]
Ah, I'm going to close this in favor of the aforementioned bug.
