### ISSUE TITLE
ctrl-c doesn't kill processes on Windows

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/multirust-rs#48]
When running around in the MSYS shell using `multirust` I've found that using Ctrl-C to kill a process (or killing multirust in any other way) doesn't actually kill the child that it spawned. This means that the Cargo process, for example, that you tried to interrupt will keep running in the background and spewing output to the console.

The way I know of at least to handle this on Windows at least is to use [`CreateJobObject`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682409%28v=vs.85%29.aspx) which is something I also ended up doing for [the bootstrap build system](https://github.com/alexcrichton/rust/blob/efe76cf6e1e303b24af7c371d7fdc1b528f15c12/src/bootstrap/build/job.rs#L52)

**Comment by brson** [comment]
Fixed.
